# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-audio-output

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Change Audio Output
Version:    0.3.0
Release:    3
Group:      Qt/Qt
License:    GPLv3
URL:        https://chris.netsoj.nl/projects/harbour-audio-output/
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-audio-output.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(libpulse)
BuildRequires:  desktop-file-utils

%description
A simple application to choose the audio output of the system.

%if "%{?vendor}" == "chum"
PackageName: Audio Output Chooser
Categories: 
  - Utility
Custom:
  Repo: https://github.com/HenkKalkwater/sailfish-audio-output
Icon: https://chris.netsoj.nl/static/img/projects/icons/harbour-audio-output.png
Screenshots:
  - https://chris.netsoj.nl/static/img/projects/images/harbour-audio-output-1.jpg
%endif


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
